# Generated by Django 5.0.1 on 2024-01-31 09:06

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseStatus",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                (
                    "Description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("IsActive", models.BooleanField()),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("IsActive", models.BooleanField(default=True)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Code", models.CharField(max_length=2)),
                ("Name", models.CharField(max_length=255)),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=20)),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("StatusName", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTypes",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=20)),
                ("Description", models.CharField(max_length=255)),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProofOfIdentty",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Type", models.CharField(max_length=255)),
                ("Value", models.CharField(max_length=255)),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingStaff",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=200)),
                ("EmailID", models.CharField(max_length=200)),
                ("IsActive", models.BooleanField()),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(blank=True, max_length=255, null=True)),
                ("UpdatedDate", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserRoles",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Description", models.CharField(max_length=255)),
                ("IsActive", models.BooleanField()),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Description", models.CharField(max_length=255)),
                ("Duration", models.IntegerField()),
                ("StartDate", models.DateField()),
                ("EndtDate", models.DateField()),
                ("StartTime", models.TimeField()),
                ("EndTime", models.TimeField()),
                ("Cost", models.IntegerField()),
                (
                    "Course_metirials",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="static/uploads/Stady_metirials",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "xls", "xlsx"]
                            )
                        ],
                    ),
                ),
                ("Course_status", models.IntegerField(default=0)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                (
                    "LanguageID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.languages",
                    ),
                ),
                (
                    "LevelID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.level",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "PaymentDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("TransactionId", models.CharField(max_length=100)),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("IsDiscountApplied", models.BooleanField()),
                ("DiscountedPayment", models.IntegerField(default=0)),
                ("Description", models.TextField(blank=True, null=True)),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(blank=True, max_length=255, null=True)),
                ("UpdatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CourseId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.courses",
                    ),
                ),
                (
                    "PaymentMethodId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.paymentmethod",
                    ),
                ),
                (
                    "PaymentStatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.paymentstatus",
                    ),
                ),
                (
                    "PaymentTypeId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.paymenttypes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                ("userid", models.CharField(blank=True, max_length=5, null=True)),
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                ("UpdatedDate", models.DateTimeField()),
                (
                    "PaymentDetails",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.payments",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payments",
            name="StudentDetails",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Inlingua_app.studentdetails",
            ),
        ),
        migrations.CreateModel(
            name="TrainingBatches",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("MeetingURL", models.CharField(max_length=500)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("Duration", models.IntegerField()),
                ("StartTime", models.TimeField()),
                ("EndTime", models.TimeField()),
                ("IsActive", models.BooleanField()),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "UpdatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(max_length=255)),
                (
                    "Course_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.courses",
                    ),
                ),
                (
                    "TrainerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.trainingstaff",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentdetails",
            name="BatchID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Inlingua_app.trainingbatches",
            ),
        ),
        migrations.CreateModel(
            name="TrainerQualifications",
            fields=[
                ("userid", models.CharField(blank=True, max_length=5, null=True)),
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("CertificateNumber", models.CharField(max_length=255)),
                ("CertifyingAuthority", models.CharField(max_length=255)),
                ("CertificateValidTill", models.DateTimeField()),
                ("TrainerHead", models.BooleanField(default=False)),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(blank=True, max_length=255, null=True)),
                ("UpdatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "LanguageID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.languages",
                    ),
                ),
                (
                    "LevelId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.level",
                    ),
                ),
                (
                    "TrainerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.trainingstaff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentBatchAllocation",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(blank=True, max_length=255, null=True)),
                ("UpdatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "BatchID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.trainingbatches",
                    ),
                ),
                (
                    "TrainerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.trainingstaff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("Mobile_Number", models.IntegerField(blank=True, null=True)),
                (
                    "user_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/Profiles/"
                    ),
                ),
                ("Address", models.CharField(blank=True, max_length=400, null=True)),
                ("created_by", models.CharField(max_length=255)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.userroles",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="trainingstaff",
            name="LoginId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="StudentStudyMetirials",
            fields=[
                (
                    "StudyMaterialID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("MaterialType", models.CharField(max_length=100)),
                ("File", models.FileField(upload_to="studymaterials")),
                ("CreatedDate", models.DateTimeField(auto_now_add=True)),
                ("uploadesdate", models.DateTimeField(auto_now_add=True)),
                (
                    "CourseID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inlingua_app.courses",
                    ),
                ),
                (
                    "UploadedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_student_studymaterials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_student_studymaterials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentdetails",
            name="StudentID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ManagementStaff",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=200)),
                ("EmailID", models.CharField(max_length=200)),
                ("IsSuperAdmin", models.BooleanField()),
                ("IsAdmin", models.BooleanField()),
                ("IsActive", models.BooleanField()),
                ("CreatedBy", models.CharField(max_length=255)),
                (
                    "CreatedDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("UpdatedBy", models.CharField(blank=True, max_length=255, null=True)),
                ("UpdatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "LoginId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
