# Generated by Django 5.0.4 on 2024-05-06 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='level_id',
            new_name='LevelID',
        ),
        migrations.AlterField(
            model_name='courses',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 40, 999248)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='UpdatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 40, 999248)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='languages',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 40, 999248)),
        ),
        migrations.AlterField(
            model_name='languages',
            name='UpdatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 40, 999248)),
        ),
        migrations.AlterField(
            model_name='level',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 40, 999248)),
        ),
        migrations.AlterField(
            model_name='level',
            name='UpdatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 40, 999248)),
        ),
        migrations.AlterField(
            model_name='managementstaff',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='PaymentDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='UpdatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='proofofidentty',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='proofofidentty',
            name='UpdatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='studentbatchallocation',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 30500)),
        ),
        migrations.AlterField(
            model_name='trainer_head_table',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='trainer_head_table',
            name='UpdatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='trainerqualifications',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='trainingbatches',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='trainingbatches',
            name='UpdatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='trainingstaff',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='UpdatedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 19, 38, 41, 14875)),
        ),
    ]
