# Generated by Django 5.0.3 on 2024-04-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbatches',
            name='trainer_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_batches_as_head', to='Inlingua_app.trainingstaff'),
        ),
    ]
