# Generated by Django 5.0.4 on 2024-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='class_active',
            field=models.BooleanField(default=False),
        ),
    ]
