# Generated by Django 5.0.1 on 2024-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inlingua_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerqualifications",
            name="userid",
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
