# Generated by Django 5.0.4 on 2024-05-03 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Assessment',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/Assessment', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='courses',
            name='Recorded_Session',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/Recorded_Session', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Course_metirials',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/Stady_metirials', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
