# Generated by Django 5.0.3 on 2024-04-02 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0002_trainingbatches_trainer_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainer_head_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsActive', models.BooleanField()),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(max_length=255)),
                ('trainer_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_head_allocations', to='Inlingua_app.trainingstaff')),
            ],
        ),
        migrations.AlterField(
            model_name='trainingbatches',
            name='trainer_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_batches_as_head', to='Inlingua_app.trainer_head_table'),
        ),
    ]
