# Generated by Django 5.0.1 on 2024-02-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inlingua_app", "0002_alter_trainerqualifications_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="userid",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="trainerqualifications",
            name="userid",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
