# Generated by Django 5.0.3 on 2024-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0003_trainer_head_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='ID',
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='StatusName',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Yet to pay', 'Yet to pay')], default='Yet to pay', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
