# Generated by Django 5.0.1 on 2024-02-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inlingua_app", "0003_alter_studentdetails_userid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="UpdatedBy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="UpdatedDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
