# Generated by Django 5.0.1 on 2024-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inlingua_app", "0004_alter_studentdetails_updatedby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_img",
            field=models.FileField(blank=True, null=True, upload_to="images/Profiles/"),
        ),
    ]
