# Generated by Django 5.0.1 on 2024-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inlingua_app", "0005_alter_user_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="Uploads/Users/Profiles/"
            ),
        ),
    ]
