# Generated by Django 5.0.1 on 2024-02-02 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inlingua_app", "0006_alter_user_email_alter_user_user_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttypes",
            name="Description",
        ),
    ]
