# Generated by Django 5.0.1 on 2024-02-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0008_studentdetails_is_active_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='CreatedDate',
            field=models.DateTimeField(),
        ),
    ]
