# Generated by Django 5.0.1 on 2024-02-15 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0009_alter_payments_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='CreatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
