# Generated by Django 5.0.1 on 2024-02-15 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0010_alter_payments_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsDiscountApplied', models.BooleanField()),
                ('DiscountedPayment', models.IntegerField(default=0)),
                ('Description', models.TextField(blank=True, null=True)),
                ('CreatedBy', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payments',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='DiscountedPayment',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='IsDiscountApplied',
        ),
    ]
