# Generated by Django 5.0.1 on 2024-02-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0011_discount_remove_payments_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='StudentDetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Inlingua_app.studentdetails'),
        ),
    ]
