# Generated by Django 5.0.1 on 2024-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0012_discount_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatches',
            name='Name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
