# Generated by Django 5.0.1 on 2024-02-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0013_alter_trainingbatches_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Description',
            field=models.TextField(max_length=255),
        ),
    ]
