# Generated by Django 5.0.1 on 2024-02-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0014_alter_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='DiscountedPayment',
            field=models.FloatField(default=0),
        ),
    ]
